version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123
    networks:
      - sameNetworkAsMysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=127.0.0.1", "--password=pass123"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  api:
    build:
      context: ./backend
    ports:
      - 3000:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - 3001:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass123
    ports:
      - 8080:80
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db

networks:
  sameNetworkAsMysql:
    driver: bridge